#!/usr/bin/env python3
"""Interactively align the Xycar steering zero with A/D key presses."""

import math
import os
from pathlib import Path
import select
import sys
import termios
import time
import tty

import rclpy
from rclpy.node import Node
from std_msgs.msg import Float32MultiArray


CALIBRATION_FILE = Path(
    '/home/xytron/noetic_ws/src/xycar_motor/config/'
    'steering_calibration.yaml')
INPUT_TO_RADIAN = 0.0068
INPUT_TO_SPEED = 0.08
MIN_INPUT = -60.64
MAX_INPUT = 60.54


def read_saved_offset():
    """Read the small calibration YAML without adding a YAML dependency."""
    try:
        for line in CALIBRATION_FILE.read_text().splitlines():
            key, separator, value = line.partition(':')
            if separator and key.strip() == 'angle_offset':
                return float(value.split('#', 1)[0].strip())
    except (OSError, ValueError):
        pass
    return 0.0


def save_offset(value):
    """Atomically save the zero offset shared with the ROS 1 motor node."""
    temporary = CALIBRATION_FILE.with_suffix('.yaml.tmp')
    content = (
        '# Generated by: ros2 run my_motor steering_center\n'
        '# Added when an application commands angle=0.\n'
        'angle_offset: {:.3f}\n'.format(value)
    )
    temporary.write_text(content)
    os.replace(temporary, CALIBRATION_FILE)


class SteeringCenter(Node):
    """Move both linked front wheels in small, zero-speed increments."""

    def __init__(self):
        super().__init__('steering_center')
        self.publisher = self.create_publisher(
            Float32MultiArray, 'xycar_motor', 1)
        self.step = float(self.declare_parameter('step', 0.5).value)
        self.test_speed = float(
            self.declare_parameter('test_speed', 5.0).value)
        self.test_seconds = float(
            self.declare_parameter('test_seconds', 4.0).value)
        if self.step <= 0.0:
            raise ValueError('step must be greater than zero')
        if self.test_speed <= 0.0 or self.test_seconds <= 0.0:
            raise ValueError('test_speed and test_seconds must be positive')
        self.saved_offset = read_saved_offset()
        self.adjustment = 0.0
        self.left_presses = 0
        self.right_presses = 0
        self.has_published = False
        self.saved = False

    def publish(self, logical_input, speed=0.0):
        message = Float32MultiArray()
        message.data = [float(logical_input), float(speed)]
        self.publisher.publish(message)
        self.has_published = True
        rclpy.spin_once(self, timeout_sec=0.01)

    def wait_for_bridge(self):
        deadline = time.monotonic() + 5.0
        while (rclpy.ok() and
               self.count_subscribers('/xycar_motor') == 0 and
               time.monotonic() < deadline):
            rclpy.spin_once(self, timeout_sec=0.1)
        return self.count_subscribers('/xycar_motor') > 0

    def show_status(self):
        total = self.saved_offset + self.adjustment
        degrees = math.degrees(-total * INPUT_TO_RADIAN)
        text = (
            '\rA(왼쪽) {:3d}회 | D(오른쪽) {:3d}회 | 순이동 {:+4d}회 | '
            '새 0점 입력 {:+7.3f} | 명령각 {:+6.2f} deg'
        ).format(
            self.left_presses,
            self.right_presses,
            self.right_presses - self.left_presses,
            total,
            degrees,
        )
        print(text, end='', flush=True)

    def stop_drive(self):
        """Send repeated zero-speed commands while holding the steering."""
        for _ in range(20):
            self.publish(self.adjustment, 0.0)
            time.sleep(0.05)

    def drive_straight_test(self):
        """Drive four seconds with the current candidate centre setting."""
        print('\n직진 시험: 현재 조향값을 유지하고 {:.1f}초 전진합니다.'.format(
            self.test_seconds))
        print('차량 전방을 비우세요. 카운트다운/주행 중 아무 키 = 취소·정지')

        for remaining in (3, 2, 1):
            print('\r{}초 후 출발...'.format(remaining), end='', flush=True)
            readable, _, _ = select.select([sys.stdin], [], [], 1.0)
            if readable:
                sys.stdin.read(1)
                print('\n직진 시험을 취소했습니다.')
                self.stop_drive()
                self.show_status()
                return

        print('\r주행 중... 아무 키를 누르면 정지합니다.       ')
        start = time.monotonic()
        deadline = start + self.test_seconds
        interrupted = False
        while rclpy.ok() and time.monotonic() < deadline:
            self.publish(self.adjustment, self.test_speed)
            readable, _, _ = select.select([sys.stdin], [], [], 0.04)
            if readable:
                sys.stdin.read(1)
                interrupted = True
                break

        elapsed = time.monotonic() - start
        self.stop_drive()
        estimated = self.test_speed * INPUT_TO_SPEED * elapsed
        if interrupted:
            print('사용자 정지: {:.2f}초 주행, 이론 거리 약 {:.2f}m'.format(
                elapsed, estimated))
        else:
            print('직진 시험 완료: {:.2f}초, 이론 거리 약 {:.2f}m'.format(
                elapsed, estimated))
        print('직진했다면 s로 저장, 휘었다면 a/d로 다시 조정하세요.')
        self.show_status()

    def run(self):
        print('조향 영점 미세조정')
        print('  a: 두 바퀴를 왼쪽으로 1단계')
        print('  d: 두 바퀴를 오른쪽으로 1단계')
        print('  w: 현재 조향값으로 저속 4초 직진 시험')
        print('  s: 현재 위치를 새 0점으로 저장하고 종료')
        print('  q: 저장하지 않고 기존 0점으로 복귀')
        print('  1단계 = {:.3f} 입력 = {:.3f} deg 명령각'.format(
            self.step, math.degrees(self.step * INPUT_TO_RADIAN)))
        print('  기존 angle_offset = {:+.3f}'.format(self.saved_offset))

        if not self.wait_for_bridge():
            print('\n안전 중지: /xycar_motor 브리지 구독자가 없습니다.')
            return
        if len(self.get_publishers_info_by_topic('/xycar_motor')) > 1:
            print('\n안전 중지: 다른 /xycar_motor 발행 노드가 실행 중입니다.')
            return

        old_terminal = termios.tcgetattr(sys.stdin.fileno())
        tty.setcbreak(sys.stdin.fileno())
        try:
            self.show_status()
            last_publish = 0.0
            while rclpy.ok():
                now = time.monotonic()
                if now - last_publish >= 0.1:
                    self.publish(self.adjustment)
                    last_publish = now

                readable, _, _ = select.select([sys.stdin], [], [], 0.05)
                if not readable:
                    continue
                key = sys.stdin.read(1).lower()
                if key == 'a':
                    proposed = self.saved_offset + self.adjustment - self.step
                    if proposed >= MIN_INPUT:
                        self.adjustment -= self.step
                        self.left_presses += 1
                    self.show_status()
                elif key == 'd':
                    proposed = self.saved_offset + self.adjustment + self.step
                    if proposed <= MAX_INPUT:
                        self.adjustment += self.step
                        self.right_presses += 1
                    self.show_status()
                elif key == 'w':
                    self.drive_straight_test()
                    last_publish = time.monotonic()
                elif key == 's':
                    new_offset = self.saved_offset + self.adjustment
                    save_offset(new_offset)
                    self.saved_offset = new_offset
                    self.adjustment = 0.0
                    self.saved = True
                    # The ROS 1 node notices the file change, so logical zero
                    # now holds the exact same physical steering position.
                    for _ in range(15):
                        self.publish(0.0)
                        time.sleep(0.05)
                    print('\n저장 완료: angle_offset = {:+.3f}'.format(
                        new_offset))
                    return
                elif key in ('q', '\x03'):
                    print('\n저장하지 않고 종료합니다.')
                    return
        finally:
            termios.tcsetattr(sys.stdin.fileno(), termios.TCSADRAIN,
                              old_terminal)


def main(args=None):
    rclpy.init(args=args)
    node = SteeringCenter()
    try:
        node.run()
    except KeyboardInterrupt:
        pass
    finally:
        # Logical zero means either the old saved centre (abort) or the newly
        # saved centre. Speed remains zero in both cases.
        if node.has_published:
            for _ in range(10):
                node.publish(0.0)
                time.sleep(0.05)
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
